  import localFont from "next/font/local";
  import { Bricolage_Grotesque } from 'next/font/google'
  import { Space_Mono } from 'next/font/google'
  import { cn } from '@/lib/utils'
  import "./globals.css";

  const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
  });
  const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
  });

  const fontHeading = Bricolage_Grotesque({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-heading',
  })

  const fontBody = Space_Mono({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-body',
    weight: ['400', '700'],
  })

  export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body
          className={cn(
            'antialiased',
            fontHeading.variable,
            fontBody.variable
          )}
        >
          {children}
        </body>
      </html>
    );
  }
